applications/entrada/urls.py
#
from django.conf import settings
from django.urls import path
from . import views
from django.conf.urls.static import static


app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas', 
        views.EntryListView.as_view(),
        name='entry-lista',
    ),
    path(
        'entradas/<pk>', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),
]

applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='index',
    ),
    path(
        'register-suscription',
        views.SuscriberCreateView.as_view(),
        name='add-suscription'
    ),
    path(
        'contact',
        views.ContactCreateView.as_view(),
        name='add-contact'
    ),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    #urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/home/models.py
from django.db import models
#app terceros
from model_utils.models import TimeStampedModel

class Home(TimeStampedModel):
    """Modelo de pagina principal"""

    tittle = models.CharField('Nombre', max_length=30)
    description = models.TextField()
    about_title = models.CharField('Sobre Nosotros', max_length=50)
    about_text = models.TextField()
    contact_email = models.EmailField('Email de contacto', blank=True, null=True)
    phone = models.CharField('Telefono de contacto', max_length=20)

    class Meta:
        verbose_name = 'Pagina principal'
        verbose_name_plural = 'Paginas principales'
    
    def __str__(self):
        return self.tittle

class Suscribers(TimeStampedModel):
    """Modelo de suscriptores"""

    email = models.EmailField()

    class Meta:
        
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'
    
        def __str__(self):
            return self.email
    
class Contact(TimeStampedModel):
    
    full_name = models.CharField('Nombres', max_length=60)
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        
        verbose_name = 'Contacto'
        verbose_name_plural = 'Mensajes'
    
        def __str__(self):
            return self.full_name

applications/home/forms.py
from django import forms
#models
from .models import Suscribers, Contact

class SuscribersForm(forms.ModelForm):
    class Meta:
        model= Suscribers
        fields = (
            'email',
        )
        widget={
            'email': forms.EmailInput(
                attrs = {
                    'placeholder': 'Correo electrónico ...',
                }
            ),
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('__all__')

        def clean(self):
            """Validaciones para el formulario"""
            usuario= self.cleaned_data['full_name']
            correo= self.cleaned_data['email']
            mensaje= self.cleaned_data['message']
        
            if len(usuario) < 1:
                self.add_error('usuario', 'No puedes enviar un mensaje vacio')
            if len(correo) < 1:
                self.add_error('correo', 'No puedes enviar un mensaje vacio')
            if len(mensaje) < 1:
                self.add_error('mensaje', 'No puedes enviar un mensaje vacio')

applications/home/views.py
from django.urls import reverse_lazy

from django.views.generic import (
    TemplateView,
    CreateView,
)
from django.contrib.messages.views import SuccessMessageMixin
#apps entrada
from applications.entrada.models import Entry
#models
from .models import Home
#forms
from .forms import SuscribersForm, ContactForm

class HomePageView(TemplateView):
    template_name = "home/index.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        #cargamos el home, en base al ultimo registro creado
        context["home"] = Home.objects.latest('created')
        #contexto de portada (entrada_en_portada es un manager)
        context["portada"] = Entry.objects.entrada_en_portada()
        #contexto para los articulos
        context["entradas_home"] = Entry.objects.entradas_en_home()
        #contexto para las entradas recientes
        context['entradas_recientes'] = Entry.objects.entradas_recientes()
        #enviamos formulario de suscripcion
        context["suscripcion"] = SuscribersForm
        return context

class SuscriberCreateView(CreateView):
    form_class = SuscribersForm
    success_url = '.'

class ContactCreateView(SuccessMessageMixin, CreateView):
    template_name = "home/index.html"
    form_class = ContactForm
    success_url = reverse_lazy("home_app:index")
    success_message = 'Mensaje enviado correctamente'

templates/home/base_home.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

templates/home/index.html
{% extends "home/base_home.html" %}

{% load static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <!-- primer bloque del home -->
    <div class="grid-x grid-margin-x" style="margin-top: 6em;">
        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6">
            <div class="card" style="width: 100%; background: #FCFCFC; box-shadow: 0px 10px 50px rgba(0, 0, 0, 0.15); border-radius: 20px;">
                <img src=" {{ portada.image.url }} ">
                <div class="card-section">
                    <h4><a href="{% url 'entrada_app:entry-detail' portada.id %}"> {{portada.title}} </a> </h4>
                    <p> {{portada.resume}} </p>
                </div>
            </div>
        </div>
        <!-- FIN bloque de blog principal -->

        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6 grid-x grid-margin-x">            
            {% for entrada  in entradas_home  %}
            <div class="cell small-12 large-6">
                <div class="card" style="width: 100%; background: #FCFCFC; box-shadow: 0px 10px 50px rgba(0, 0, 0, 0.15); border-radius: 20px;"">
                    <img src=" {{entrada.image.url}} " style="height:120px; ">
                    <div class="card-section">
                        <a href="{% url 'entrada_app:entry-detail' entrada.id %}"><h5> {{entrada.title | truncatechars:60}} </h5></a> 
                    </div>
                </div>
            </div>                
            {% endfor %}                
        </div>
        <!-- FIN bloque de blog principal -->
    </div>
    <!-- FIN del primer bloque home -->

    <!-- segundo bloque pantalla home -->
    <div class="grid-x align-center" style="margin-top: 1em; background: linear-gradient(94.23deg, #6B54FA -2.64%, #DD6B6B 90.08%); box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25); border-radius: 300px; border-radius: 300px;">
        <div class="cell small-12 large-10 " style="margin-top: 1em; font-family:cambria; font-size: 20px; color: #ffffff; text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">
            <h5><strong>{{home.about_title}}</strong> </h5>
            <div class="cell small-12 large-10" style="font-family:cambria; font-size: 15px; color: #ffffff;">
            <p>
                {{home.about_text}}
            </p>
            </div>
            <p>
                <button class="button" data-open="exampleModal2" style="font-family:cambria; font-size: 18px; color: #ffffff; text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25); background: linear-gradient(89.52deg, rgba(166, 19, 236, 0) -1.13%, rgba(222, 31, 253, 0) 99.75%);
                border: 4px solid #F5F5F5;
                border-radius: 20px;
                box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
                border-radius: 300px;">¡Unete a nosotros!</button>
            </p>

            <!-- This is the first modal -->
            <div class="reveal" id="exampleModal2" data-reveal style="width: 300px;">
                <p class="lead">Ingresa tu correo</p>
                <form class="grid-x grid-margin-x" method="POST" action="{%url 'home_app:add-suscription'%}">{% csrf_token %}
                    <div class="cell small-12">
                        {{suscripcion.email}}
                    </div>
                    <div class="cell small-12">
                        <button type="submit" class="success button">Suscribete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- FIN segundo bloque pantalla home -->


    <!-- tercer bloque home -->
    <div class="grid-x grid-margin-x align-center" style="margin-top: 2em; ">
        <h3 style="font-family:cambria; font-size: 30px; color: #010851; text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);" class="cell">
            Articulos Recientes
        </h3>
        {% for entrada in entradas_recientes %}
        <div class="cell small-6 large-4">
            <div class="card" style="width: 100%; background: #FCFCFC;
            box-shadow: 0px 10px 50px rgba(0, 0, 0, 0.15); border-radius: 20px;">
                <img src=" {{entrada.image.url}}" style="height:200px;">
                <div class="card-section">
                <a href="{% url 'entrada_app:entry-detail' entrada.id %}"><h5> {{entrada.title | truncatechars:60}} </h5> </a>
                    <p> {{entrada.resume | truncatechars:70}} </p>
                </div>
            </div>        
        </div>
        {% endfor %}
    </div>
    <!-- FIN tercer bloque -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}