applications/entrada/urls.py
#
from django.conf import settings
from django.urls import path
from . import views
from django.conf.urls.static import static


app_name = "entrada_app"

urlpatterns = [
    path(
        'entradas', 
        views.EntryListView.as_view(),
        name='entry-lista',
    ),
    path(
        'entradas/<pk>', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),
]

applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='index',
    ),
    path(
        'register-suscription',
        views.SuscriberCreateView.as_view(),
        name='add-suscription'
    ),
    path(
        'contact',
        views.ContactCreateView.as_view(),
        name='add-contact'
    ),
]

applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entrada.urls')),
    re_path('', include('applications.favoritos.urls')),
    #urls para ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/home/models.py
from django.db import models
#app terceros
from model_utils.models import TimeStampedModel

class Home(TimeStampedModel):
    """Modelo de pagina principal"""

    tittle = models.CharField('Nombre', max_length=30)
    description = models.TextField()
    about_title = models.CharField('Sobre Nosotros', max_length=50)
    about_text = models.TextField()
    contact_email = models.EmailField('Email de contacto', blank=True, null=True)
    phone = models.CharField('Telefono de contacto', max_length=20)

    class Meta:
        verbose_name = 'Pagina principal'
        verbose_name_plural = 'Paginas principales'
    
    def __str__(self):
        return self.tittle

class Suscribers(TimeStampedModel):
    """Modelo de suscriptores"""

    email = models.EmailField()

    class Meta:
        
        verbose_name = 'Suscriptor'
        verbose_name_plural = 'Suscriptores'
    
        def __str__(self):
            return self.email
    
class Contact(TimeStampedModel):
    
    full_name = models.CharField('Nombres', max_length=60)
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        
        verbose_name = 'Contacto'
        verbose_name_plural = 'Mensajes'
    
        def __str__(self):
            return self.full_name

templates/includes/footer.html
{% load static %}
<div class="grid-x align-center"
  style="margin-top: 1em; background: linear-gradient(94.23deg, #6B54FA -2.64%, #DD6B6B 90.08%); box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">
  <div class="cell small-12 large-10 " style="margin-top: 1em; color: #ffffff;">
    <div class="grid-x grid-padding-x align-center">
      <h3 class="cell small-12 large-7"
        style="font-family:cambria; font-size: 30px; color: #ffffff; text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">
        <strong>Formulario de contacto</strong>
      </h3>
      <form class="cell small-12 large-7" method="POST" action="{% url 'home_app:add-contact' %}"> 
        {% csrf_token %}
        {% for error in field.errors %}
          {{ error }}
        {% endfor %}
          <div class="grid-x grid-padding-x" style="margin-top: 1em;">
            <div class="medium-4 cell">
              <label style="font-family:cambria; font-size: 15px; color: #ffffff;">Usuario
                <input type="text" placeholder="Nombre de usuario" name="full_name" id="id_full_name">
              </label>
            </div>
            <div class="medium-4 cell">
              <label style="font-family:cambria; font-size: 15px; color: #ffffff;">Correo
                <input type="email" placeholder="Correo electrónico" name="email" id="id_email">
              </label>
            </div>
            <div class="medium-8 cell">
              <label style="font-family:cambria; font-size: 15px; color: #ffffff;">Mensaje
                <textarea placeholder="Escribe tu mensaje aquí" name="message" id="id_message"></textarea>
              </label>
              {% if messages %}
              {% for message in messages %}
              <div class="callout success">
                <div class="grid-x align-center ">
                  <p>
                    <li class="{{ message.tags }}">{{ message }}</li>
                  </p>
                </div>
              </div>
              {% endfor %}
              </ul>
              {% endif %}
            </div>
            <div class="medium-12 cell">
              <p>
                <button class="button" style="margin-top: -0.1em; font-family:cambria; font-size: 18px; color: #ffffff; background: linear-gradient(89.52deg, rgba(166, 19, 236, 0) -1.13%, rgba(222, 31, 253, 0) 99.75%);
                border: 4px solid #F5F5F5;
                border-radius: 20px;
                box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
                border-radius: 300px;">Enviar</button>
              </p>
            </div>
          </div>
      </form>
      <div class="container">
        <p class="cell large-2"
          style="font-family:cambria; font-size: 24px; color: #ffffff; text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">
          <strong>Otras formas de contacto</strong>
        </p>
        <p class="cell large-8" style="font-family:cambria; font-size: 20px;">
        <p style="color: #ffffff"> <strong>Correo:</strong>
          <span style="font-family:cambria; font-size: 15px; color: #ffffff;"> {{ correo }}</span>
        </p>
        <p style="color: #ffffff"> <strong>Teléfono:</strong>
          <span style="font-family:cambria; font-size: 15px; color: #ffffff;"> {{ phone }}</span>
        </p>
        </p>
        <div class="social">
          <p class="cell large-2"
            style="font-family:cambria; font-size: 20px; color: #ffffff; text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">
            <strong>Redes sociales</strong>
          </p>
          <a href="https://www.facebook.com/gabriela.duarte.71619/"><img src="{% static 'img/facebook.png' %}"
              style="width:35px;"></a>
          <a href="https://www.instagram.com/baghi27/"><img src="{% static 'img/instagrani.png' %}"
              style="width:35px;"></a>
          <a
            href="https://api.whatsapp.com/send?phone=5493517518734&text=Quiero%20informacion%20sobre%20tu%20blog%20por%20favor"><img
              src="{% static 'img/whatsapp.png' %}" style="width:35px;"></a>
        </div>
      </div>
    </div>
  </div>

templates/includes/header.html
<header>
    <div class="grid-x grid-margin-x" style="position: fixed;
    width: 2130px;
    height: 60px;
    left: 10px;
    top: 0px; background: linear-gradient(94.23deg, #6B54FA -2.64%, #DD6B6B 90.08%);
    border-radius: 0px 0px 0px 0px;">
        <div class="cell small-12 medium-4 large-4">
            <a href=" {% url 'home_app:index' %} " style="font-family:cambria; font-size: 40px; color: #ffffff; text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">
                <strong> Pankēki-World </strong>
            </a>
        </div>
        <div class="cell small-10 medium-3">
            <div class="cell small-5 medium-4" style="margin-top: 1em; font-family:cambria; font-size: 18px; color: #ffffff; text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">
                ¡Bienvenidos a tu blog favorito de anime y manga!
            </div>
        </div>
        <div class="cell small-12 large-5">
            <ul class="menu" style="margin-top: 0.5em; justify-content: flex-end;">
                <li>
                    <a style="font-family:cambria; font-size: 18px; color: #ffffff;" class="clear button secondary" href="{%url 'home_app:index'%}">Inicio</a>
                </li>
                <li>
                    <a style="font-family:cambria; font-size: 18px;color: #ffffff;" class="clear button secondary" href="{%url 'entrada_app:entry-lista'%}">Entradas</a>
                </li>
                <li>
                    <a style="font-family:cambria; font-size: 18px;color: #ffffff;" class="clear button secondary" href="#">Foro</a>
                </li>
                <li>
                    <a style="font-family:cambria; font-size: 18px;color: #ffffff;" class="clear button secondary" href="#">Nosotros</a>
                </li>
                <li>
                    <a style="font-family:cambria; font-size: 18px;color: #ffffff; text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.5);" class="clear button" href="{% url 'users_app:user-register' %}">Registrate acá</a>
                </li>
                <li>
                    <a style="margin-top: -0.1em; font-family:cambria; font-size: 18px; color: #ffffff; background: linear-gradient(89.52deg, rgba(166, 19, 236, 0) -1.13%, rgba(222, 31, 253, 0) 99.75%);
                    border: 4px solid #F5F5F5; border-radius: 300px;" href="{% url 'users_app:user-login' %}">Inicia sesión</a>
                </li>
            </ul>
        </div>
    </div>
</header>